
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/***************************************************************
* file: EndScreen.java
* author: Joseph Gunderson & Magloire Pungi
* class: CS 245 – Programming Graphical User Interfaces
*
* assignment: Quarter Project v1.0
* date last modified: 8/11/2016
*
* purpose: Display final score
*
****************************************************************/ 

public class EndScreen extends javax.swing.JPanel {

    // save score
    private int yourScore = Play.getScore();
    // save winning initials
    private String winningName = "";
    // load high scores into 2D arrayList
    private ArrayList<ArrayList<String>> highScores = loadHighScores();
    // index to insert score at
    private int index;
    
    public EndScreen() {
        initComponents();
        jPanel2.setVisible(false);
        
        // transfer score from play screen
        jLabel2.setText(String.valueOf(yourScore));
        
        // checks if score is worthy of High Score status
        index = isHighScore();
        
        // if index is positive, ask user for their initials
        if( index >= 0 )
        {
            jLabel3.setText("Enter your initials:");
            jPanel2.setVisible(true);       
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        enter = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Game Over");

        JButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButton1.setText("End");
        JButton1.setToolTipText("");
        JButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                End(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 46)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("YOU LOSE !!");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 46)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("XXX");

        enter.setText("Record Name");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(JButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    // returns index if score qualifies, else returns -1 if unqualified
    private int isHighScore()
    {
        // if score is less than or equal to lowest score
        if( yourScore <= Integer.parseInt(highScores.get(4).get(1)) )
        {
            return -1;
        }
        
        // if score greater than highest score
        else if( yourScore > Integer.parseInt(highScores.get(0).get(1)) )
        {
            return 0;
        }
        // if score is somewhere in between, return index where to be inserted
        // (starting with lowest high score)
        else{
            for(int i=highScores.size()-1; i>0; --i)
            {
                if( yourScore > Integer.parseInt(highScores.get(i).get(1)) 
                        &&  yourScore <= Integer.parseInt(highScores.get(i-1).get(1)) )
                {
                    return i;
                }
            }
        }
        
        // if something went wrong
        return -2;
    }
    
    
    // reads from a file and returns a 2D array
    private ArrayList<ArrayList<String>> loadHighScores()
    {
        ArrayList<ArrayList<String>> highScores = new ArrayList<>();
        try{
            BufferedReader in = new BufferedReader(new FileReader("Top5.txt"));
            String s = in.readLine();
            int i=0;
            while(s != null)
            {
                // parse string by space and add to 2D Array
                String[] str = s.split("\\s+"); 
                highScores.add(new ArrayList<String>());
                highScores.get(i).add(str[0]);
                highScores.get(i).add(str[1]);
                
                // read next line
                s = in.readLine();
                ++i;
            }
            in.close();
        }catch (IOException ex) 
        {
            Logger.getLogger(HighScores.class.getName()).log(Level.SEVERE, null, ex);
        } 
            
        return highScores;
    }
    
    // updates array containing high scores
    private void updateHighScores()
    {
        try{
            BufferedWriter out = new BufferedWriter(new FileWriter("Top5.txt"));
            
            // just copy over unchanged high scores (starting with first place)
            for(int i=0; i<index; ++i)
            {
                out.write(highScores.get(i).get(0)+ " "+ highScores.get(i).get(1));
                out.newLine(); // continue writing to file in newLine
            }
            
            // copy over new high score
            out.write(winningName+ " "+ String.valueOf(yourScore));
            out.newLine();
            
            // demote remaining high scores 
            for(int i=index; i<highScores.size()-1; ++i)
            {
                out.write(highScores.get(i).get(0)+ " "+ highScores.get(i).get(1));
                out.newLine();
            }            
            // close BufferWriter
            out.close();
        }catch (IOException ex) 
        {
            Logger.getLogger(HighScores.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    
    // button that ends screen
    private void End(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_End
        // Dispose of current screen and open function buttons screen
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        JFrame f = new JFrame("Main Menu");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.add(new SecondPage());
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_End

    // saves initials from TextField and then updates saved HighScores file
    private void Enter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter
        winningName = jTextField1.getText();
        enter.setEnabled(false);
        jTextField1.setEnabled(false);
        updateHighScores();
    }//GEN-LAST:event_Enter


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton1;
    private javax.swing.JButton enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
