
import javax.swing.*;
import java.util.*;
import java.awt.event.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.util.Calendar;
//import java.util.GregorianCalendar;

//importing this for drawing
import java.awt.*;
import javax.swing.border.Border;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MagloireRaphaelo
 */
public class Play extends javax.swing.JPanel {

    private String randomWord;
    private String displayWord = "_";
    private int score = 100;
    
    
    //Implementing the body part
    boolean headDrawn = false;
    boolean bodyDrawn = false;
    boolean leftArm = false;
    boolean rightArm = false;
    boolean leftleg = false;
    boolean rightleg = false;
    boolean Noose = false;
    
    Draw draw = null;
    //keep track of how many time they got it wrong
    int nbrWrongGeusses= 0;
    //body part
    int bodyPart= 6;
    int next = 0;
    
    //implemeting the pole
    private int baseWidth = 200;
    private int baseHeight = 20;
    private int poleWidth = 20;
    
    //this is for the model
    private Play model;
    
    /**
     * Creates new form Play
     */
    public Play() {
        
        String[] words = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        
        initComponents();
       
        // Display Clock
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //...Perform a task...
                Calendar cal = new GregorianCalendar();
                int month = cal.get(Calendar.MONTH);
                int day = cal.get(Calendar.DATE);
                int year = cal.get(Calendar.YEAR);
                int hour = cal.get(Calendar.HOUR);
                int min = cal.get(Calendar.MINUTE);
                int seconds = cal.get(Calendar.SECOND);
                String clock= month + "/" + day + "/" + year + " " + hour +":"+ min +":"+ seconds ;
                jLabel2.setText(clock);
            }
        };
        
        // set timer to continuously update
        javax.swing.Timer timer = new javax.swing.Timer(0,taskPerformer);
        timer.setRepeats(true);
        timer.start();
        
        // randomly generate word to guess
        Random r = new Random();
        randomWord = words[r.nextInt(words.length)];
        
        // displays blank spaces for word to be guessed
        for(int i=0; i<randomWord.length()-1; ++i)
        {
            displayWord = displayWord + ' ' + '_';
        }

        // updates all display variables
        updateDisplay();
        
        System.out.println(randomWord);
        
        //his.model = model;
        //this.setPreferredSize(new Dimension());//3 
                //this.setBackground(Color.WHITE)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        skip = new javax.swing.JButton();
        c = new javax.swing.JButton();
        b = new javax.swing.JButton();
        a = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        l = new javax.swing.JButton();
        v = new javax.swing.JButton();
        w = new javax.swing.JButton();
        u = new javax.swing.JButton();
        k = new javax.swing.JButton();
        j = new javax.swing.JButton();
        d = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        x = new javax.swing.JButton();
        y = new javax.swing.JButton();
        s = new javax.swing.JButton();
        t = new javax.swing.JButton();
        z = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        word = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HANGMAN");

        skip.setText("Skip");
        skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Skip(evt);
            }
        });

        c.setText("C");
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c(evt);
            }
        });

        b.setText("B");
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b(evt);
            }
        });

        a.setText("A");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a(evt);
            }
        });

        e.setText("E");
        e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e(evt);
            }
        });

        f.setText("F");
        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f(evt);
            }
        });

        g.setText("G");
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g(evt);
            }
        });

        h.setText("H");
        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h(evt);
            }
        });

        i.setText("I");
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i(evt);
            }
        });

        l.setText("L");
        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l(evt);
            }
        });

        v.setText("V");
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v(evt);
            }
        });

        w.setText("W");
        w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w(evt);
            }
        });

        u.setText("U");
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u(evt);
            }
        });

        k.setText("K");
        k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                k(evt);
            }
        });

        j.setText("J");
        j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j(evt);
            }
        });

        d.setText("D");
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d(evt);
            }
        });

        m.setText("M");
        m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M(evt);
            }
        });

        n.setText("N");
        n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n(evt);
            }
        });

        o.setText("O");
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o(evt);
            }
        });

        p.setText("P");
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p(evt);
            }
        });

        q.setText("Q");
        q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q(evt);
            }
        });

        r.setText("R");
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r(evt);
            }
        });

        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x(evt);
            }
        });

        y.setText("Y");
        y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y(evt);
            }
        });

        s.setText("S");
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s(evt);
            }
        });

        t.setText("T");
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t(evt);
            }
        });

        z.setText("Z");
        z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Z(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Score.setBackground(new java.awt.Color(0, 0, 0));
        Score.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Score.setForeground(new java.awt.Color(255, 255, 255));
        Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score.setText("100");
        Score.setToolTipText("");

        word.setBackground(new java.awt.Color(0, 0, 0));
        word.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        word.setForeground(new java.awt.Color(255, 255, 255));
        word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(k)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(u)
                                                .addGap(18, 18, 18)
                                                .addComponent(v)
                                                .addGap(18, 18, 18)
                                                .addComponent(w)
                                                .addGap(18, 18, 18)
                                                .addComponent(x)
                                                .addGap(18, 18, 18)
                                                .addComponent(y)
                                                .addGap(18, 18, 18)
                                                .addComponent(z))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(l)
                                                .addGap(18, 18, 18)
                                                .addComponent(m)
                                                .addGap(18, 18, 18)
                                                .addComponent(n)
                                                .addGap(18, 18, 18)
                                                .addComponent(o)
                                                .addGap(18, 18, 18)
                                                .addComponent(p)
                                                .addGap(18, 18, 18)
                                                .addComponent(q)
                                                .addGap(18, 18, 18)
                                                .addComponent(r)
                                                .addGap(10, 10, 10)
                                                .addComponent(s)
                                                .addGap(18, 18, 18)
                                                .addComponent(t))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(word, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a)
                                            .addGap(18, 18, 18)
                                            .addComponent(b)
                                            .addGap(18, 18, 18)
                                            .addComponent(c)
                                            .addGap(18, 18, 18)
                                            .addComponent(d)
                                            .addGap(18, 18, 18)
                                            .addComponent(e)
                                            .addGap(18, 18, 18)
                                            .addComponent(f)
                                            .addGap(18, 18, 18)
                                            .addComponent(g)
                                            .addGap(18, 18, 18)
                                            .addComponent(h)
                                            .addGap(18, 18, 18)
                                            .addComponent(i)
                                            .addGap(18, 18, 18)
                                            .addComponent(j)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 186, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(skip)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(skip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d)
                    .addComponent(e)
                    .addComponent(f)
                    .addComponent(g)
                    .addComponent(h)
                    .addComponent(i)
                    .addComponent(j))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l)
                    .addComponent(m)
                    .addComponent(n)
                    .addComponent(o)
                    .addComponent(p)
                    .addComponent(q)
                    .addComponent(r)
                    .addComponent(s)
                    .addComponent(k)
                    .addComponent(t))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u)
                    .addComponent(v)
                    .addComponent(w)
                    .addComponent(x)
                    .addComponent(y)
                    .addComponent(z))
                .addContainerGap())
        );

        Score.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    boolean match = false;
    // returns true if char in randomWord
    private boolean checkWord(char c)
    {
        for(int i=0; i<randomWord.length(); ++i)
        {
            if(c == randomWord.charAt(i))
            {
                return true;
                          
            }
        }
        return false;
    }
    
    // updates display word with correctly guessed character
    private void updateDisplayWord(char c)
    {
        for(int i=0; i<randomWord.length(); ++i)
        {
            if(randomWord.charAt(i) == c)
            {
                displayWord = displayWord.substring(0,i*2) + c + " " + 
                            displayWord.substring((i+1)*2,displayWord.length());
                //error coming from the y because it is outofbound
            }
        } 
    }
    
    // updates all display variables
    private void updateDisplay()
    {
        word.setText(displayWord);
        Score.setText(String.valueOf(score));            
    }
    
    
    
//    private void partOfBody(){
//        
//    }
    
    //painting the different part of the body
//    protected void paintComponent(Graphics g){
//        super.paintComponent (g);
//        Color clr = Color.BLACK;
//        Color color = Color.BLACK;
//        g.setColor(clr);
//        
//        switch (model.nbrWrong()){
//            case 10:
//                color = Color.red;
//                Noose(g, color);
//            case 10:
//                color = Color.red;
//                Noose(g, color);
//            case 10:
//                color = Color.red;
//                Noose(g, color);
//            case 10:
//                color = Color.red;
//                Noose(g, color);
//            case 10:
//                color = Color.red;
//                drawLeftArm(g, color);
//            case 5:
//                color = Color.red;
//                drawBody(g, color);
//            case 4:
//                color = Color.red;
//                drawHead(g, color);
//            case 3:
//                color = Color.red;
//                drawHeader(g, color);
//            case 2:
//                color = Color.red;
//                drawPole(g, color);
//            case 1:
//                color = Color.red;
//                drawBase(g, color);
                
                
                
            
       // }
        
        
    //}
    public Component centerPane(){
        draw = new Draw(this);
        return draw;
    }
   public Component comp(){
       JPanel pane = new JPanel();
       pane.setLayout(new BorderLayout());
       pane.add(centerPane(), BorderLayout.CENTER);
       return pane;
   }
    private void Skip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Skip
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        JFrame f = new JFrame("Hangman");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.add(new HighScores());
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_Skip

    private void a(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a
        // disables button after being pressed
     
                a.setEnabled(false);
            
        // checks if letter in word
        nbrWrongGeusses++;
        if ( checkWord('a') )
        {
            updateDisplayWord( 'a' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();        
        
    }//GEN-LAST:event_a

    private void b(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b
        // disables button after being pressed
        
                b.setEnabled(false);
          
        // checks if letter in word
        if ( checkWord('b') )
        {
            updateDisplayWord( 'b' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_b

    private void c(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c
        // TODO add your handling code here:
         
          c.setEnabled(false);

        // checks if letter in word
        if ( checkWord('c') )
        {
            updateDisplayWord( 'c' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_c

    private void d(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d
        // TODO add your handling code here:
         
                d.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('d') )
        {
            updateDisplayWord( 'd' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_d

    private void e(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e
        // TODO add your handling code here:
          e.setEnabled(false);

           
        // checks if letter in word
        if ( checkWord('e') )
        {
            updateDisplayWord( 'e' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_e

    private void f(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f
        // TODO add your handling code here:
        
                f.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('f') )
        {
            updateDisplayWord( 'f' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_f

    private void g(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g
        // TODO add your handling code here:
        
                g.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('g') )
        {
            updateDisplayWord( 'g' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_g

    private void h(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h
        // TODO add your handling code here:
         
                h.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('h') )
        {
            updateDisplayWord( 'h' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_h

    private void i(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i
        // TODO add your handling code here:
        
                i.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('i') )
        {
            updateDisplayWord( 'i' );
            
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_i

    private void j(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j
        // TODO add your handling code here:
       
                j.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('j') )
        {
            updateDisplayWord( 'j' );
            
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_j

    private void k(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k
        // TODO add your handling code here:
         
                k.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('k') )
        {
            updateDisplayWord( 'k' );
            
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_k

    private void l(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l
        // TODO add your handling code here:
         
                l.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('l') )
        {
            updateDisplayWord( 'l' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_l

    private void n(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n
        // TODO add your handling code here:
         
                n.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('n') )
        {
            updateDisplayWord( 'n' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_n

    private void o(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o
        // TODO add your handling code here:
       
                o.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('o') )
        {
            updateDisplayWord( 'o' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_o

    private void p(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p
        // TODO add your handling code here:
        
                p.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('p') )
        {
            updateDisplayWord( 'p' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_p

    private void q(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q
        // TODO add your handling code here:
       
                q.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('q') )
        {
            updateDisplayWord( 'q' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_q

    private void r(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r
        // TODO add your handling code here:
       
                r.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('r') )
        {
            updateDisplayWord( 'r' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_r

    private void s(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s
        // TODO add your handling code here:
        
                s.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('s') )
        {
            updateDisplayWord( 's' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_s

    private void t(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t
        // TODO add your handling code here:
       
                t.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('t') )
        {
            updateDisplayWord( 't' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_t

    private void u(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u
        // TODO add your handling code here:
        
                u.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('u') )
        {
            updateDisplayWord( 'u' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_u

    private void v(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v
        // TODO add your handling code here:
        
                v.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('v') )
        {
            updateDisplayWord( 'v' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_v

    private void w(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w
        // TODO add your handling code here:
      
                w.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('w') )
        {
            updateDisplayWord( 'w' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_w

    private void x(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x
        // TODO add your handling code here:
       
                x.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('x') )
        {
            updateDisplayWord( 'x' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_x

    private void y(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y
        // TODO add your handling code here:
       
                y.setEnabled(false);
            
        // checks if letter in word
        if ( checkWord('Y') )
        {
            updateDisplayWord( 'Y' ); //issue here
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_y

    private void Z(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Z
        // TODO add your handling code here:
        
                z.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('z') )
        {
            updateDisplayWord( 'z' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
    }//GEN-LAST:event_Z

    private void M(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M
        // TODO add your handling code here:
        
                m.setEnabled(false);
           
        // checks if letter in word
        if ( checkWord('m') )
        {
            updateDisplayWord( 'm' );
        }
        else{
            score -= 10;
            //draw body part
            switch (nbrWrongGeusses){
                case 1: {headDrawn = false; break;}
                case 2: {bodyDrawn = false; break;}
                case 3: {leftArm = false; break;}
                case 4: {rightArm = false; break;}
                case 5: {leftleg = false; break;}
                case 6: {rightleg = false; break;}             
            }
          draw.repaint();
        }
        // updates dispaly variables
        updateDisplay();  
        
    }//GEN-LAST:event_M
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Score;
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton skip;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JLabel word;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables

    private int nbrWrong() {
        return nbrWrongGeusses;
    }

    
    }
    
    
    
    
    
    

