
//import javax.swing.JFrame;
//import javax.swing.SwingUtilities;

import javax.swing.*;
import java.util.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MagloireRaphaelo
 */
public class Play extends javax.swing.JPanel {

    /**
     * Creates new form Play
     */
    public Play() {
        
        String[] words = {"abstract", "cemetery", "nurse", "pharmacy", "climbing"};
        
        initComponents();
       
        // Display Clock
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //...Perform a task...
                Calendar cal = new GregorianCalendar();
                int month = cal.get(Calendar.MONTH);
                int day = cal.get(Calendar.DATE);
                int year = cal.get(Calendar.YEAR);
                int hour = cal.get(Calendar.HOUR);
                int min = cal.get(Calendar.MINUTE);
                int seconds = cal.get(Calendar.SECOND);
                String clock= month + "/" + day + "/" + year + " " + hour +":"+ min +":"+ seconds ;
                jLabel2.setText(clock);
            }
        };
        
        // set timer to continuously update
        javax.swing.Timer timer = new javax.swing.Timer(0,taskPerformer);
        timer.setRepeats(true);
        timer.start();
        
        // randomly generate word to guess
        Random r = new Random();
        String randomWord = words[r.nextInt(words.length)];
        
        // displays blank spaces for word to be guessed
        String display = "_";
        for(int i=0; i<randomWord.length()-1; ++i)
        {
            display = display + ' ' + '_';
        }
        word.setText(display);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        skip = new javax.swing.JButton();
        c = new javax.swing.JButton();
        b = new javax.swing.JButton();
        a = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        l = new javax.swing.JButton();
        v = new javax.swing.JButton();
        w = new javax.swing.JButton();
        u = new javax.swing.JButton();
        k = new javax.swing.JButton();
        j = new javax.swing.JButton();
        d = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        x = new javax.swing.JButton();
        y = new javax.swing.JButton();
        s = new javax.swing.JButton();
        t = new javax.swing.JButton();
        z = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        word = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Pristina", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HANGMAN");

        skip.setText("Skip");
        skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Skip(evt);
            }
        });
        skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipActionPerformed(evt);
            }
        });

        c.setText("C");
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c(evt);
            }
        });

        b.setText("B");
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b(evt);
            }
        });

        a.setText("A");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        e.setText("E");
        e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e(evt);
            }
        });

        f.setText("F");
        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f(evt);
            }
        });

        g.setText("G");
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g(evt);
            }
        });

        h.setText("H");
        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h(evt);
            }
        });

        i.setText("I");
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i(evt);
            }
        });

        l.setText("L");
        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l(evt);
            }
        });

        v.setText("V");
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v(evt);
            }
        });

        w.setText("W");
        w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                w(evt);
            }
        });

        u.setText("U");
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u(evt);
            }
        });

        k.setText("K");
        k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                k(evt);
            }
        });

        j.setText("J");
        j.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j(evt);
            }
        });

        d.setText("D");
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d(evt);
            }
        });

        m.setText("M");
        m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMouseClicked(evt);
            }
        });
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M(evt);
            }
        });

        n.setText("N");
        n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n(evt);
            }
        });

        o.setText("O");
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o(evt);
            }
        });

        p.setText("P");
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p(evt);
            }
        });

        q.setText("Q");
        q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                q(evt);
            }
        });

        r.setText("R");
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r(evt);
            }
        });

        x.setText("X");
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x(evt);
            }
        });

        y.setText("Y");
        y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y(evt);
            }
        });

        s.setText("S");
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s(evt);
            }
        });

        t.setText("T");
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t(evt);
            }
        });

        z.setText("Z");
        z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Z(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Score.setBackground(new java.awt.Color(0, 0, 0));
        Score.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Score.setForeground(new java.awt.Color(255, 255, 255));
        Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score.setText("100");
        Score.setToolTipText("");

        word.setBackground(new java.awt.Color(0, 0, 0));
        word.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        word.setForeground(new java.awt.Color(255, 255, 255));
        word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(k)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(u)
                                                .addGap(18, 18, 18)
                                                .addComponent(v)
                                                .addGap(18, 18, 18)
                                                .addComponent(w)
                                                .addGap(18, 18, 18)
                                                .addComponent(x)
                                                .addGap(18, 18, 18)
                                                .addComponent(y)
                                                .addGap(18, 18, 18)
                                                .addComponent(z))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(l)
                                                .addGap(18, 18, 18)
                                                .addComponent(m)
                                                .addGap(18, 18, 18)
                                                .addComponent(n)
                                                .addGap(18, 18, 18)
                                                .addComponent(o)
                                                .addGap(18, 18, 18)
                                                .addComponent(p)
                                                .addGap(18, 18, 18)
                                                .addComponent(q)
                                                .addGap(18, 18, 18)
                                                .addComponent(r)
                                                .addGap(10, 10, 10)
                                                .addComponent(s)
                                                .addGap(18, 18, 18)
                                                .addComponent(t))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(word, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a)
                                            .addGap(18, 18, 18)
                                            .addComponent(b)
                                            .addGap(18, 18, 18)
                                            .addComponent(c)
                                            .addGap(18, 18, 18)
                                            .addComponent(d)
                                            .addGap(18, 18, 18)
                                            .addComponent(e)
                                            .addGap(18, 18, 18)
                                            .addComponent(f)
                                            .addGap(18, 18, 18)
                                            .addComponent(g)
                                            .addGap(18, 18, 18)
                                            .addComponent(h)
                                            .addGap(18, 18, 18)
                                            .addComponent(i)
                                            .addGap(18, 18, 18)
                                            .addComponent(j)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(skip)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(skip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(word, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(b)
                    .addComponent(c)
                    .addComponent(d)
                    .addComponent(e)
                    .addComponent(f)
                    .addComponent(g)
                    .addComponent(h)
                    .addComponent(i)
                    .addComponent(j))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l)
                    .addComponent(m)
                    .addComponent(n)
                    .addComponent(o)
                    .addComponent(p)
                    .addComponent(q)
                    .addComponent(r)
                    .addComponent(s)
                    .addComponent(k)
                    .addComponent(t))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u)
                    .addComponent(v)
                    .addComponent(w)
                    .addComponent(x)
                    .addComponent(y)
                    .addComponent(z))
                .addContainerGap())
        );

        Score.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    
    private void checkWord(char c)
    {
        
    }
    
    
    private void Skip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Skip
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        JFrame f = new JFrame("Hangman");
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.add(new HighScores());
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_Skip

    private void a(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a
    a.addActionListener(new ActionListener() {
     public void actionPerformed(ActionEvent ae) {
        a.setEnabled(false);
        //bA.setEnabled(true);
     }
   }
 );
       
    }//GEN-LAST:event_a

    private void b(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b
        // TODO add your handling code here:
        b.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent be){
                b.setEnabled(false);
            }
        });
    }//GEN-LAST:event_b

    private void c(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c
        // TODO add your handling code here:
         c.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ce){
                c.setEnabled(false);
            }
        });
    }//GEN-LAST:event_c

    private void d(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d
        // TODO add your handling code here:
         d.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent de){
                d.setEnabled(false);
            }
        });
    }//GEN-LAST:event_d

    private void e(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e
        // TODO add your handling code here:
         e.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ee){
                e.setEnabled(false);
            }
        });
    }//GEN-LAST:event_e

    private void f(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f
        // TODO add your handling code here:
         f.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent fe){
                f.setEnabled(false);
            }
        });
    }//GEN-LAST:event_f

    private void g(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g
        // TODO add your handling code here:
         g.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ge){
                g.setEnabled(false);
            }
        });
    }//GEN-LAST:event_g

    private void h(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h
        // TODO add your handling code here:
         h.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent he){
                h.setEnabled(false);
            }
        });
    }//GEN-LAST:event_h

    private void i(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i
        // TODO add your handling code here:
         i.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ie){
                i.setEnabled(false);
            }
        });
    }//GEN-LAST:event_i

    private void j(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j
        // TODO add your handling code here:
         j.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent je){
                j.setEnabled(false);
            }
        });
    }//GEN-LAST:event_j

    private void k(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k
        // TODO add your handling code here:
         k.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ke){
                k.setEnabled(false);
            }
        });
    }//GEN-LAST:event_k

    private void l(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l
        // TODO add your handling code here:
         l.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent le){
                l.setEnabled(false);
            }
        });
    }//GEN-LAST:event_l

    private void n(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n
        // TODO add your handling code here:
         n.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ne){
                n.setEnabled(false);
            }
        });
    }//GEN-LAST:event_n

    private void o(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o
        // TODO add your handling code here:
        o.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent oe){
                o.setEnabled(false);
            }
        });
    }//GEN-LAST:event_o

    private void p(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p
        // TODO add your handling code here:
        p.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent pe){
                p.setEnabled(false);
            }
        });
    }//GEN-LAST:event_p

    private void q(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_q
        // TODO add your handling code here:
        q.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent qe){
                q.setEnabled(false);
            }
        });
    }//GEN-LAST:event_q

    private void r(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r
        // TODO add your handling code here:
        r.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent re){
                r.setEnabled(false);
            }
        });
    }//GEN-LAST:event_r

    private void s(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s
        // TODO add your handling code here:
        s.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent se){
                s.setEnabled(false);
            }
        });
    }//GEN-LAST:event_s

    private void t(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t
        // TODO add your handling code here:
        t.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent te){
                t.setEnabled(false);
            }
        });
    }//GEN-LAST:event_t

    private void u(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u
        // TODO add your handling code here:
        u.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ue){
                u.setEnabled(false);
            }
        });
    }//GEN-LAST:event_u

    private void v(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v
        // TODO add your handling code here:
        v.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ve){
                v.setEnabled(false);
            }
        });
    }//GEN-LAST:event_v

    private void w(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_w
        // TODO add your handling code here:
        w.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent we){
                w.setEnabled(false);
            }
        });
    }//GEN-LAST:event_w

    private void x(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x
        // TODO add your handling code here:
        x.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent xe){
                x.setEnabled(false);
            }
        });
    }//GEN-LAST:event_x

    private void y(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y
        // TODO add your handling code here:
        y.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ye){
                y.setEnabled(false);
            }
        });
    }//GEN-LAST:event_y

    private void Z(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Z
        // TODO add your handling code here:
        z.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ze){
                z.setEnabled(false);
            }
        });
    }//GEN-LAST:event_Z

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_aActionPerformed

    private void skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skipActionPerformed

    private void mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mMouseClicked

    private void M(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M
        // TODO add your handling code here:
        m.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent me){
                m.setEnabled(false);
            }
        });
    }//GEN-LAST:event_M
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Score;
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton skip;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JLabel word;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}
